"""Adicionando a coluna cnpj, e user type

Revision ID: 2854b0e65daf
Revises: 3df6880999c5
Create Date: 2024-11-30 22:30:26.408987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2854b0e65daf'
down_revision: Union[str, None] = '3df6880999c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
