"""Adicionando a coluna cnpj, e user type

Revision ID: 3df6880999c5
Revises: fea72325cff1
Create Date: 2024-11-30 18:40:33.464802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3df6880999c5'
down_revision: Union[str, None] = 'fea72325cff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cnpj', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.Enum('PF', 'PJ', name='user_type_enum'), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['cnpj'])
    op.create_unique_constraint(None, 'users', ['cpf'])
    op.alter_column('works', 'activities',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'activities',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'cnpj')
    # ### end Alembic commands ###
