"""Add hash password 

Revision ID: 9445a12a7758
Revises: d4b7b2c6fb52
Create Date: 2024-11-11 20:53:39.301157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9445a12a7758'
down_revision: Union[str, None] = 'd4b7b2c6fb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
