"""Adicionando a coluna cnpj, e user type

Revision ID: fea72325cff1
Revises: da2aa9635edf
Create Date: 2024-11-30 18:32:46.300215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'fea72325cff1'
down_revision: Union[str, None] = 'da2aa9635edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_type_enum = ENUM('PF', 'PJ', name='user_type_enum', create_type=True)
    user_type_enum.create(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # Remove a coluna user_type
    op.drop_column('users', 'user_type')

    # Exclui o tipo ENUM
    user_type_enum = ENUM('PF', 'PJ', name='user_type_enum')
    user_type_enum.drop(op.get_bind())
